const marketOptions = [
  { id:'atlas', name:'Atlas Components', quantity:300, days:6, cost:4500, spec:'exact', note:'On time, but only 300 units available.' },
  { id:'beacon', name:'Beacon Industrial', quantity:500, days:11, cost:8400, spec:'exact', note:'Full quantity and under budget, but 4 days late.' },
  { id:'cobalt', name:'Cobalt Supply', quantity:200, days:6, cost:5900, spec:'exact', note:'Can fill the 200-unit gap on time, but expensive.' },
  { id:'delta', name:'Delta Motion', quantity:500, days:5, cost:8200, spec:'substitute', note:'Fast and under budget, but requires a substitute model.' },
  { id:'echo', name:'Echo Reserve', quantity:100, days:5, cost:1200, spec:'exact', note:'Recovery-only reserve with MOQ 100.' }
];
const goalContract = Object.freeze({ quantityMin:500, deliveryMaxDays:7, baseBudget:8500, exactSpecRequired:true, finalCommitRequiresHuman:true });
const plans = [
  { id:'plan_cost', label:'Preserve deadline + exact spec', className:'cost', composition:['Atlas 300','Cobalt 200'], quantity:500, days:6, cost:10400, spec:'exact', tradeoff:'Budget +$1,900', summary:'Split across Atlas and Cobalt. Meets quantity, deadline, and exact specification.' },
  { id:'plan_time', label:'Preserve budget + exact spec', className:'time', composition:['Beacon 500'], quantity:500, days:11, cost:8400, spec:'exact', tradeoff:'Deadline +4 days', summary:'Cheapest exact-spec plan, but misses the 7-day deadline.' },
  { id:'plan_spec', label:'Preserve deadline + budget', className:'spec', composition:['Delta 500'], quantity:500, days:5, cost:8200, spec:'substitute', tradeoff:'Substitute model', summary:'Fastest and under budget, but changes the sensor specification.' }
];
const policies = {
  plan_cost:{ planId:'plan_cost', label:'Keep deadline + exact spec', budgetCap:10500, deadlineMaxDays:7, exactSpecRequired:true, overbuyPercent:10, rationale:'Allow up to $2,000 extra, split orders, and up to 10% overbuy for bounded recovery.' },
  plan_time:{ planId:'plan_time', label:'Keep budget + exact spec', budgetCap:8500, deadlineMaxDays:11, exactSpecRequired:true, overbuyPercent:0, rationale:'Accept a 4-day deadline extension while preserving budget and exact specification.' },
  plan_spec:{ planId:'plan_spec', label:'Keep deadline + budget', budgetCap:8500, deadlineMaxDays:7, exactSpecRequired:false, overbuyPercent:0, rationale:'Allow the approved substitute model while preserving deadline and budget.' }
};
const els = Object.fromEntries(['webmcpStatus','runDemoBtn','resetBtn','lockGoalBtn','contractSeal','marketEmpty','supplierList','rawPlanCount','rejectedPlanCount','decisionPlanCount','planGrid','decisionGrid','decisionStatus','executionState','repairFlow','gateProof','gateProofStatus','gateProofResult','gateProofCode','gateProofCopy','finalApprovalBox','finalApprovalCopy','finalApproveBtn','receiptEmpty','receipt','receiptSummary','metricOptions','metricDecisions','metricRepairs','receiptId','timeline','toolChips','demoNarration','stageGoal','stageExplore','stagePlans','stageDecision','stageRepair','stageCommit','stageEvidence','contractPanel','marketPanel','planSection','decisionSection','executionPanel','authorityPanel','evidencePanel'].map(id=>[id,document.getElementById(id)]));
const freshState = () => ({ goalLocked:false, marketDiscovered:false, plansGenerated:false, plansVerified:false, decisionRequested:false, decisionAuthorized:false, selectedPlanId:null, policy:null, executionStarted:false, disruptionInjected:false, repaired:false, repairedPlan:null, finalApprovalRequested:false, finalApproved:false, committed:false, receiptId:null, toolCalls:0, humanDecisions:0, repairs:0, events:[] });
let state = freshState(); let demoRunning = false; const sleep = ms => new Promise(r=>setTimeout(r,ms));
const stageIds=['stageGoal','stageExplore','stagePlans','stageDecision','stageRepair','stageCommit','stageEvidence'];
function nowLabel(){ return new Date().toLocaleTimeString([], {hour12:false,hour:'2-digit',minute:'2-digit',second:'2-digit'}); }
function addEvent(kind,message){ state.events.unshift({at:nowLabel(),kind,message}); state.events=state.events.slice(0,12); renderTimeline(); }
function countTool(name){ state.toolCalls++; addEvent('tool',`WebMCP · ${name}`); }
function setStage(active,narration,focusEl=null){ stageIds.forEach((id,i)=>{els[id].classList.toggle('complete',i<active);els[id].classList.toggle('active',i===active)}); els.demoNarration.textContent=narration; [els.contractPanel,els.marketPanel,els.executionPanel,els.authorityPanel,els.evidencePanel].forEach(el=>el.classList.remove('demo-active')); if(focusEl?.classList?.contains('panel')) focusEl.classList.add('demo-active'); }
function focusDemo(el){ if(el) el.scrollIntoView({behavior:'smooth',block:'center'}); }
function renderTimeline(){ els.timeline.innerHTML=state.events.map(e=>`<div class="event ${e.kind}"><span>${e.at}</span><span>${e.message}</span></div>`).join(''); }
function renderMarket(){ els.marketEmpty.classList.add('hidden'); els.supplierList.innerHTML=marketOptions.slice(0,4).map(o=>`<div class="supplier"><div><h3>${o.name}</h3><div class="supplier-meta"><span>${o.quantity} units</span><span>${o.days} days</span><span>$${o.cost.toLocaleString()}</span><span>${o.spec==='exact'?'exact spec':'substitute model'}</span></div></div><div class="supplier-constraint">${o.note}</div></div>`).join(''); }
function renderPlans(){ els.rawPlanCount.textContent='17'; els.rejectedPlanCount.textContent='14'; els.decisionPlanCount.textContent='3'; els.planGrid.innerHTML=plans.map(p=>`<article class="plan-card ${p.className}"><span class="plan-kicker">${p.label}</span><h3>${p.composition.join(' + ')}</h3><p class="plan-summary">${p.summary}</p><div class="plan-metrics"><div><b>${p.quantity}</b><small>units</small></div><div><b>${p.days}d</b><small>arrival</small></div><div><b>$${p.cost.toLocaleString()}</b><small>cost</small></div></div><div class="tradeoff">${p.tradeoff}</div></article>`).join(''); }
function renderDecisionPackage(){ els.decisionGrid.innerHTML=plans.map(p=>{const rec=p.id==='plan_cost',policy=policies[p.id];return `<article class="decision-card ${p.className} ${rec?'recommended':''}"><span class="plan-kicker">${p.label}</span><h3>${p.tradeoff}</h3><p>${policy.rationale}</p>${rec?'<span class="recommended-label">RECOMMENDED · PRESERVES DEADLINE + SPEC</span>':''}<button class="decision-button" data-authorize-plan="${p.id}">Authorize this trade-off</button></article>`}).join(''); els.decisionGrid.querySelectorAll('[data-authorize-plan]').forEach(b=>b.addEventListener('click',()=>humanAuthorizePlan(b.dataset.authorizePlan))); }
function renderExecutionState(icon,title,copy){ els.executionState.innerHTML=`<span class="state-icon">${icon}</span><div><strong>${title}</strong><p>${copy}</p></div>`; }
function repairStep(kind,title,copy){ els.repairFlow.insertAdjacentHTML('beforeend',`<div class="repair-step ${kind}"><strong>${title}</strong>${copy}</div>`); }
function renderGate(mode='waiting'){ els.gateProof.classList.remove('blocked','committed'); if(mode==='blocked'){els.gateProof.classList.add('blocked');els.gateProofStatus.textContent='LIVE ENFORCEMENT PROOF';els.gateProofResult.textContent='BLOCKED';els.gateProofCode.textContent='FINAL_COMMIT_APPROVAL_REQUIRED';els.gateProofCopy.textContent='The plan is verified and inside the trade-off envelope, but irreversible commitment still requires a second human decision.';return;} if(mode==='committed'){els.gateProof.classList.add('committed');els.gateProofStatus.textContent='FINAL AUTHORITY SATISFIED';els.gateProofResult.textContent='COMMITTED';els.gateProofCode.textContent='DECISION → REPAIR → APPROVAL → PASS';els.gateProofCopy.textContent='The agent repaired inside authorized bounds, then committed only after explicit final human approval.';return;} els.gateProofStatus.textContent='NOT REACHED';els.gateProofResult.textContent='WAITING';els.gateProofCode.textContent='FINAL_COMMIT_APPROVAL_REQUIRED'; }
function makeReceiptId(){ const seed=`${state.selectedPlanId}|${state.repairedPlan?.quantity}|${state.repairedPlan?.cost}|${state.toolCalls}|${state.humanDecisions}`; let h=2166136261; for(const ch of seed) h=Math.imul(h^ch.charCodeAt(0),16777619); return `VMC-${(h>>>0).toString(16).padStart(8,'0').toUpperCase()}`; }
function renderReceipt(){ if(!state.committed){els.receiptEmpty.classList.remove('hidden');els.receipt.classList.add('hidden');return;} els.receiptEmpty.classList.add('hidden');els.receipt.classList.remove('hidden');els.receiptSummary.textContent=`${state.repairedPlan.quantity} exact-spec sensors · ${state.repairedPlan.days} days · $${state.repairedPlan.cost.toLocaleString()} · trade-off + repair + final approval recorded`;els.metricOptions.textContent='17';els.metricDecisions.textContent=String(state.humanDecisions);els.metricRepairs.textContent=String(state.repairs);els.receiptId.textContent=state.receiptId; }
function lockGoalContract(){ state.goalLocked=true;els.contractSeal.textContent='Goal Contract locked · 500 units / 7 days / $8,500 / exact spec';els.contractSeal.classList.add('locked');els.lockGoalBtn.disabled=true;addEvent('human','Human locked the original Goal Contract');return {ok:true,contract:{...goalContract}}; }
function requireGoal(){ return state.goalLocked?null:{ok:false,error:'GOAL_CONTRACT_NOT_LOCKED',next:'Human must lock the Goal Contract first.'}; }
function toolGetGoalContract(){countTool('get_goal_contract');const b=requireGoal();if(b)return b;return {ok:true,contract:{...goalContract},authority:'Agent may explore, generate, verify, and repair. Human judgment is required for trade-offs and irreversible final commitment.'};}
function toolDiscover(){countTool('discover_fulfillment_options');const b=requireGoal();if(b)return b;state.marketDiscovered=true;renderMarket();addEvent('tool','Market discovered · no single option satisfies every original constraint');return {ok:true,options:marketOptions.slice(0,4)};}
function toolGenerate(){countTool('generate_candidate_plans');if(!state.marketDiscovered)return {ok:false,error:'MARKET_NOT_DISCOVERED'};state.plansGenerated=true;renderPlans();addEvent('tool','17 combinations generated · compressed to 3 non-dominated human-relevant plans');return {ok:true,raw_plan_count:17,rejected_or_dominated:14,frontier:plans};}
function evaluate(p){return {quantity:p.quantity>=500,deadline:p.days<=7,budget:p.cost<=8500,exact_spec:p.spec==='exact'};}
function toolVerify(){countTool('verify_candidate_plans');if(!state.plansGenerated)return {ok:false,error:'PLANS_NOT_GENERATED'};state.plansVerified=true;const verified=plans.map(p=>({plan_id:p.id,checks:evaluate(p),full_pass:Object.values(evaluate(p)).every(Boolean),tradeoff:p.tradeoff}));addEvent('fail','No zero-trade-off plan satisfies all original constraints');return {ok:true,original_goal_feasible:false,verified,decision_required:true};}
function toolRequestDecision(){countTool('request_human_decision');if(!state.plansVerified)return {ok:false,error:'PLANS_NOT_VERIFIED'};state.decisionRequested=true;renderDecisionPackage();addEvent('human','Human Decision Package requested · 3 meaningful trade-offs');return {ok:true,status:'AWAITING_HUMAN_TRADEOFF_DECISION',decisions:plans.map(p=>({plan_id:p.id,tradeoff:p.tradeoff,summary:p.summary})),note:'This tool cannot authorize a trade-off. Human UI action is required.'};}
function humanAuthorizePlan(planId){if(!state.decisionRequested||!policies[planId])return false;state.decisionAuthorized=true;state.selectedPlanId=planId;state.policy={...policies[planId]};state.humanDecisions++;els.decisionStatus.classList.add('authorized');els.decisionStatus.textContent=`AUTHORIZED · ${state.policy.label} · ${state.policy.rationale}`;els.decisionGrid.querySelectorAll('button').forEach(b=>b.disabled=true);addEvent('human',`Human authorized trade-off envelope · ${state.policy.label}`);if(planId==='plan_cost')continueCostPlan();else continueSimplePlan(planId);return true;}
async function continueCostPlan(){setStage(4,'Decision recorded. AI executes — then a new real-world problem appears.',els.executionPanel);focusDemo(els.executionPanel);state.executionStarted=true;renderExecutionState('RUN','Executing Atlas 300 + Cobalt 200','Human authorized extra budget to preserve deadline and exact specification.');repairStep('pass','Plan authorized','Atlas 300 + Cobalt 200 · 500 units · 6 days · $10,400');await sleep(1100);injectDisruption();await sleep(1000);toolRepairPlan();await sleep(1000);toolRequestFinalApproval();demoRunning=false;}
async function continueSimplePlan(id){setStage(4,'Alternative trade-off authorized. This branch is valid; the recommended branch demonstrates repair.',els.executionPanel);focusDemo(els.executionPanel);state.executionStarted=true;const p=plans.find(x=>x.id===id);state.repaired=true;state.repairedPlan={...p,composition:[...p.composition]};renderExecutionState('PASS','Authorized plan ready',p.summary);repairStep('pass','No repair required',p.summary);await sleep(700);toolRequestFinalApproval();demoRunning=false;}
function injectDisruption(){if(state.selectedPlanId!=='plan_cost'||state.disruptionInjected)return;state.disruptionInjected=true;renderExecutionState('!','Execution changed: Cobalt drops 200 → 150','The selected plan now delivers only 450 units. Mission Control must repair a 50-unit gap without reopening every decision.');repairStep('fail','Execution disruption','Cobalt availability fell from 200 to 150. Current plan: 450 / 500 units.');addEvent('fail','Execution disruption · Cobalt shortfall creates a 50-unit gap');}
function policyAllows(p){if(!state.policy)return false;const maxQ=Math.floor(500*(1+state.policy.overbuyPercent/100));return p.quantity>=500&&p.quantity<=maxQ&&p.days<=state.policy.deadlineMaxDays&&p.cost<=state.policy.budgetCap&&(!state.policy.exactSpecRequired||p.spec==='exact');}
function toolRepairPlan(){countTool('repair_plan');if(!state.decisionAuthorized)return {ok:false,error:'HUMAN_DECISION_REQUIRED'};if(state.selectedPlanId!=='plan_cost'){return {ok:true,repair_needed:false,plan:state.repairedPlan};}if(!state.disruptionInjected)return {ok:false,error:'NO_EXECUTION_FAILURE_TO_REPAIR'};const p={id:'plan_cost_repaired',composition:['Atlas 300','Cobalt 150','Echo Reserve 100'],quantity:550,days:6,cost:10125,spec:'exact'};if(!policyAllows(p))return {ok:false,error:'REPAIR_OUTSIDE_AUTHORIZED_ENVELOPE',plan:p};state.repaired=true;state.repairs++;state.repairedPlan=p;renderExecutionState('PASS','Plan repaired inside authorized bounds','AI preserves Atlas 300 + Cobalt 150 and adds Echo Reserve MOQ 100. Final quantity 550 stays inside the authorized 10% overbuy envelope.');repairStep('pass','Autonomous local repair','Atlas 300 + Cobalt 150 + Echo 100 = 550 exact-spec units · 6 days · $10,125.');repairStep('pass','Authority check','≤ 7 days ✅ · ≤ $10,500 cap ✅ · exact spec ✅ · ≤ 10% overbuy ✅');addEvent('pass','Plan repaired without expanding the human-approved authority envelope');setStage(5,'Repair succeeded inside the authorized envelope. Final commitment is still human-controlled.',els.authorityPanel);return {ok:true,repaired:true,plan:p,authority_check:'PASS',human_reapproval_required_for_repair:false};}
function toolRequestFinalApproval(){countTool('request_final_approval');if(!state.repaired||!state.repairedPlan)return {ok:false,error:'PLAN_NOT_READY'};state.finalApprovalRequested=true;renderGate('blocked');els.finalApprovalBox.classList.remove('hidden');els.finalApprovalCopy.textContent=`${state.repairedPlan.composition.join(' + ')} · ${state.repairedPlan.quantity} units · ${state.repairedPlan.days} days · $${state.repairedPlan.cost.toLocaleString()}.`;addEvent('human','Final irreversible commitment requires explicit human approval');focusDemo(els.authorityPanel);return {ok:true,status:'AWAITING_FINAL_HUMAN_APPROVAL',plan:state.repairedPlan};}
function humanApproveFinal(){if(!state.finalApprovalRequested||!state.repaired)return false;state.finalApproved=true;state.humanDecisions++;els.finalApprovalBox.classList.add('hidden');addEvent('human','Human approved final irreversible commitment');return true;}
function toolCommitPlan(){countTool('commit_plan');if(!state.decisionAuthorized)return {ok:false,error:'HUMAN_TRADEOFF_DECISION_REQUIRED'};if(!state.repaired||!state.repairedPlan)return {ok:false,error:'PLAN_NOT_VERIFIED_READY'};if(!state.finalApproved){renderGate('blocked');addEvent('fail','Commit blocked · FINAL_COMMIT_APPROVAL_REQUIRED');return {ok:false,error:'FINAL_COMMIT_APPROVAL_REQUIRED',next:'Wait for explicit human final approval.'};}if(!policyAllows(state.repairedPlan))return {ok:false,error:'FINAL_PLAN_OUTSIDE_AUTHORIZED_ENVELOPE'};state.committed=true;state.receiptId=makeReceiptId();renderGate('committed');renderReceipt();addEvent('pass','Goal achieved · repaired plan committed inside human authority');setStage(7,'Mission complete. The receipt explains the goal, trade-off, repair, approvals, and final outcome.',els.evidencePanel);focusDemo(els.evidencePanel);return {ok:true,status:'GOAL_ACHIEVED',final_plan:state.repairedPlan,receipt_id:state.receiptId};}
function toolReceipt(){countTool('get_evidence_receipt');return {ok:true,goal_status:state.committed?'PASS':'IN_PROGRESS',original_goal:{...goalContract},market_options_explored:state.marketDiscovered?4:0,plan_compression:state.plansGenerated?{raw:17,rejected_or_dominated:14,human_relevant:3}:null,human_tradeoff_decision:state.policy?{...state.policy}:null,execution_disruption:state.disruptionInjected?'Cobalt 200 -> 150':null,autonomous_repair:state.repairedPlan,final_human_approval:state.finalApproved,human_decisions:state.humanDecisions,receipt_id:state.receiptId,recent_events:state.events.slice(0,8)};}
const emptySchema={type:'object',properties:{},additionalProperties:false};
const toolDefinitions=[
{name:'get_goal_contract',title:'Read Goal Contract',description:'Read the locked human goal, hard constraints, and authority model before planning.',inputSchema:emptySchema,annotations:{readOnlyHint:true},execute:toolGetGoalContract},
{name:'discover_fulfillment_options',title:'Discover Fulfillment Options',description:'Discover market options and quantity, delivery, cost, and specification constraints.',inputSchema:emptySchema,annotations:{readOnlyHint:false},execute:toolDiscover},
{name:'generate_candidate_plans',title:'Generate Candidate Plans',description:'Compose options into candidate plans and compress the meaningful frontier.',inputSchema:emptySchema,annotations:{readOnlyHint:false},execute:toolGenerate},
{name:'verify_candidate_plans',title:'Verify Candidate Plans',description:'Verify each candidate plan against the original Goal Contract and identify its required trade-off.',inputSchema:emptySchema,annotations:{readOnlyHint:false},execute:toolVerify},
{name:'request_human_decision',title:'Request Human Trade-off Decision',description:'Present meaningful trade-offs to the human. This tool cannot authorize any trade-off itself.',inputSchema:emptySchema,annotations:{readOnlyHint:false},execute:toolRequestDecision},
{name:'repair_plan',title:'Repair Authorized Plan',description:'Repair execution locally while staying inside the human-authorized decision envelope.',inputSchema:emptySchema,annotations:{readOnlyHint:false},execute:toolRepairPlan},
{name:'request_final_approval',title:'Request Final Approval',description:'Stop at the irreversible action boundary and request explicit human approval.',inputSchema:emptySchema,annotations:{readOnlyHint:false},execute:toolRequestFinalApproval},
{name:'commit_plan',title:'Commit Final Plan',description:'Commit only when the plan is verified, inside authorized bounds, and final human approval is present.',inputSchema:emptySchema,annotations:{readOnlyHint:false},execute:toolCommitPlan},
{name:'get_evidence_receipt',title:'Get Decision Provenance Receipt',description:'Read the original goal, plan compression, human decision, repair lineage, final approval, and outcome.',inputSchema:emptySchema,annotations:{readOnlyHint:true},execute:toolReceipt}
];
function renderToolChips(){els.toolChips.innerHTML=toolDefinitions.map(t=>`<span class="tool-chip">${t.name}()</span>`).join('');}
async function registerWebMCPTools(){const mc=document.modelContext;if(!mc?.registerTool){els.webmcpStatus.innerHTML='<span class="dot"></span>WebMCP preview mode';return false;}try{for(const t of toolDefinitions)await mc.registerTool(t);els.webmcpStatus.classList.add('ready');els.webmcpStatus.innerHTML=`<span class="dot"></span>${toolDefinitions.length} WebMCP tools live`;addEvent('pass',`${toolDefinitions.length} native WebMCP tools registered`);return true;}catch(e){console.error(e);els.webmcpStatus.innerHTML='<span class="dot"></span>WebMCP registration error';return false;}}
function resetMission(){state=freshState();demoRunning=false;els.lockGoalBtn.disabled=false;els.contractSeal.textContent='Contract unlocked';els.contractSeal.classList.remove('locked');els.marketEmpty.classList.remove('hidden');els.supplierList.innerHTML='';els.rawPlanCount.textContent='0';els.rejectedPlanCount.textContent='0';els.decisionPlanCount.textContent='0';els.planGrid.innerHTML='';els.decisionGrid.innerHTML='';els.decisionStatus.classList.remove('authorized');els.decisionStatus.textContent='No human trade-off decision recorded.';renderExecutionState('WAIT','Waiting for an authorized plan','Execution starts only after the human decision package is resolved.');els.repairFlow.innerHTML='';renderGate('waiting');els.finalApprovalBox.classList.add('hidden');els.receipt.classList.add('hidden');els.receiptEmpty.classList.remove('hidden');renderTimeline();stageIds.forEach(id=>els[id].classList.remove('active','complete'));els.demoNarration.textContent='Ready — press Run the decision demo';els.runDemoBtn.disabled=false;els.runDemoBtn.textContent='Run the decision demo';}
async function runDecisionDemo(){if(demoRunning)return;resetMission();demoRunning=true;els.runDemoBtn.disabled=true;els.runDemoBtn.textContent='AI exploring...';setStage(0,'Human defines the outcome and authority boundary.',els.contractPanel);focusDemo(els.contractPanel);lockGoalContract();await sleep(650);toolGetGoalContract();setStage(1,'AI explores the market. Every option solves some constraints and fails others.',els.marketPanel);focusDemo(els.marketPanel);await sleep(650);toolDiscover();await sleep(1100);setStage(2,'AI composes 17 combinations, removes weak routes, and compresses them to 3 meaningful trade-offs.');focusDemo(els.planSection);toolGenerate();await sleep(850);toolVerify();await sleep(1100);setStage(3,'No zero-trade-off answer exists. Human judgment is required — but only for 3 compressed choices.');focusDemo(els.decisionSection);toolRequestDecision();els.runDemoBtn.textContent='Waiting for human trade-off';demoRunning=false;}
els.lockGoalBtn.addEventListener('click',()=>{if(!state.goalLocked)lockGoalContract()});els.runDemoBtn.addEventListener('click',runDecisionDemo);els.resetBtn.addEventListener('click',resetMission);els.finalApproveBtn.addEventListener('click',async()=>{if(!humanApproveFinal())return;setStage(6,'Final human approval recorded. The same commit tool may now complete.',els.authorityPanel);await sleep(650);const r=toolCommitPlan();if(r.ok){toolReceipt();els.runDemoBtn.disabled=false;els.runDemoBtn.textContent='Replay decision demo';}});
window.verifiedMissionControl={get state(){return state},resetMission,lockGoalContract,humanAuthorizePlan,humanApproveFinal,runDecisionDemo,tools:Object.fromEntries(toolDefinitions.map(t=>[t.name,t.execute]))};
renderToolChips();resetMission();registerWebMCPTools();
