import { scenarios, defaultScenarioId } from './scenarios.mjs';
import { evaluatePlan, compressDecisionFrontier, createAuthorityEnvelope, authorityAllows, chooseAuthorizedRepair } from './decision-engine.mjs';

const ids=['webmcpStatus','runDemoBtn','resetBtn','lockGoalBtn','contractSeal','marketEmpty','supplierList','rawPlanCount','rejectedPlanCount','decisionPlanCount','planGrid','decisionGrid','decisionStatus','executionState','repairFlow','gateProof','gateProofStatus','gateProofResult','gateProofCode','gateProofCopy','finalApprovalBox','finalApprovalCopy','finalApproveBtn','receiptEmpty','receipt','receiptSummary','metricOptions','metricDecisions','metricRepairs','receiptId','timeline','toolChips','demoNarration','stageGoal','stageExplore','stagePlans','stageDecision','stageRepair','stageCommit','stageEvidence','contractPanel','marketPanel','planSection','decisionSection','executionPanel','authorityPanel','evidencePanel','nativeExecutionMode','nativeTrace','scenarioSwitcher','scenarioNote','goalTitle','goalCard','optionTitle','optionIntro'];
const els=Object.fromEntries(ids.map(id=>[id,document.getElementById(id)]));
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
const stageIds=['stageGoal','stageExplore','stagePlans','stageDecision','stageRepair','stageCommit','stageEvidence'];
let currentScenarioId=defaultScenarioId, demoRunning=false;
let nativeModelContext=null,nativeToolsByName={},nativeExecutionReady=false,registrationPromise=null;
const scenario=()=>scenarios[currentScenarioId];
const freshState=()=>({scenarioId:currentScenarioId,goalLocked:false,optionsDiscovered:false,plansGenerated:false,plansVerified:false,compression:null,frontier:[],decisionRequested:false,decisionAuthorized:false,selectedPlanId:null,authorityEnvelope:null,executionStarted:false,disruptionInjected:false,repaired:false,repairedPlan:null,finalApprovalRequested:false,finalApproved:false,committed:false,receiptId:null,toolCalls:0,humanDecisions:0,repairs:0,events:[]});
let state=freshState();
function nowLabel(){return new Date().toLocaleTimeString([],{hour12:false,hour:'2-digit',minute:'2-digit',second:'2-digit'});}
function addEvent(kind,message){state.events.unshift({at:nowLabel(),kind,message});state.events=state.events.slice(0,14);renderTimeline();}
function countTool(name){state.toolCalls++;addEvent('tool',`WebMCP · ${name}`);}
function resetNativeTrace(){els.nativeTrace.innerHTML='<div class="trace-empty">Run the demo to see document.modelContext.executeTool() calls and machine-readable results.</div>';}
function traceTool(name,input,result,mode){const empty=els.nativeTrace.querySelector('.trace-empty');if(empty)empty.remove();const preview=JSON.stringify(result);const row=document.createElement('div');row.className='trace-row';row.innerHTML=`<span class="trace-mode">${mode}</span><code>${name}()</code><small>${input}</small><b>→</b><pre>${preview.length>220?preview.slice(0,217)+'…':preview}</pre>`;els.nativeTrace.prepend(row);while(els.nativeTrace.children.length>6)els.nativeTrace.lastElementChild.remove();}
async function invokeTool(name,args={}){const def=toolDefinitions.find(t=>t.name===name);if(!def)throw new Error(`Unknown tool ${name}`);if(registrationPromise)await registrationPromise;if(nativeExecutionReady&&nativeToolsByName[name]){const input=JSON.stringify(args);const raw=await nativeModelContext.executeTool(nativeToolsByName[name],input);let result=raw;try{if(typeof raw==='string')result=JSON.parse(raw)}catch{}traceTool(name,input,result,'NATIVE');return result;}const result=await def.execute(args);traceTool(name,JSON.stringify(args),result,'PREVIEW');return result;}
function setStage(active,narration,focusEl=null){stageIds.forEach((id,i)=>{els[id].classList.toggle('complete',i<active);els[id].classList.toggle('active',i===active)});els.demoNarration.textContent=narration;[els.contractPanel,els.marketPanel,els.executionPanel,els.authorityPanel,els.evidencePanel].forEach(el=>el.classList.remove('demo-active'));if(focusEl?.classList?.contains('panel'))focusEl.classList.add('demo-active');}
function focusDemo(el){if(el)el.scrollIntoView({behavior:'smooth',block:'center'});}
function renderTimeline(){els.timeline.innerHTML=state.events.map(e=>`<div class="event ${e.kind}"><span>${e.at}</span><span>${e.message}</span></div>`).join('');}
function fmtMetric(def,value){return def.format?def.format(value):String(value);}
function renderScenarioShell(){const s=scenario();els.scenarioNote.innerHTML=`<span>${s.badge}</span> ${s.description}`;els.goalTitle.textContent=s.goal.title;els.optionTitle.textContent=s.optionTitle;els.optionIntro.textContent=s.optionIntro;els.goalCard.innerHTML=s.goal.constraints.map(c=>`<div><span>${c.label}</span><strong>${c.display}</strong></div>`).join('');els.scenarioSwitcher.querySelectorAll('[data-scenario]').forEach(b=>b.classList.toggle('active',b.dataset.scenario===currentScenarioId));}
function renderOptions(){const s=scenario();els.marketEmpty.classList.add('hidden');els.supplierList.innerHTML=s.options.map(o=>`<div class="supplier"><div><h3>${o.name}</h3><div class="supplier-meta">${o.meta.map(x=>`<span>${x}</span>`).join('')}</div></div><div class="supplier-constraint">${o.note}</div></div>`).join('');}
function renderPlans(){const s=scenario(),frontier=state.frontier;els.rawPlanCount.textContent=String(s.candidates.length);els.rejectedPlanCount.textContent=String(state.compression?.rejected??0);els.decisionPlanCount.textContent=String(frontier.length);els.planGrid.innerHTML=frontier.map((p,i)=>`<article class="plan-card ${['cost','time','spec'][i%3]}"><span class="plan-kicker">${p.label}</span><h3>${p.composition.join(' + ')}</h3><p class="plan-summary">${p.summary}</p><div class="plan-metrics">${s.metricDefs.map(d=>`<div><b>${fmtMetric(d,p.metrics[d.field])}</b><small>${d.label}</small></div>`).join('')}</div><div class="tradeoff">${p.tradeoff}</div></article>`).join('');}
function renderDecisionPackage(){const s=scenario();els.decisionGrid.innerHTML=state.frontier.map((p,i)=>{const rec=p.id===s.recommendedPlanId,auth=s.authorityByPlan[p.id];return `<article class="decision-card ${['cost','time','spec'][i%3]} ${rec?'recommended':''}"><span class="plan-kicker">${p.label}</span><h3>${p.tradeoff}</h3><p>${auth.rationale}</p>${rec?'<span class="recommended-label">RECOMMENDED · MAXIMUM GOAL PRESERVATION</span>':''}<button class="decision-button" data-authorize-plan="${p.id}">Authorize this trade-off</button></article>`}).join('');els.decisionGrid.querySelectorAll('[data-authorize-plan]').forEach(b=>b.addEventListener('click',()=>humanAuthorizePlan(b.dataset.authorizePlan)));}
function renderExecutionState(icon,title,copy){els.executionState.innerHTML=`<span class="state-icon">${icon}</span><div><strong>${title}</strong><p>${copy}</p></div>`;}
function repairStep(kind,title,copy){els.repairFlow.insertAdjacentHTML('beforeend',`<div class="repair-step ${kind}"><strong>${title}</strong>${copy}</div>`);}
function renderGate(mode='waiting'){els.gateProof.classList.remove('blocked','committed');if(mode==='blocked'){els.gateProof.classList.add('blocked');els.gateProofStatus.textContent='LIVE ENFORCEMENT PROOF';els.gateProofResult.textContent='BLOCKED';els.gateProofCode.textContent='FINAL_COMMIT_APPROVAL_REQUIRED';els.gateProofCopy.textContent='The plan is verified and inside the human-authorized envelope, but irreversible commitment still requires explicit approval.';return;}if(mode==='committed'){els.gateProof.classList.add('committed');els.gateProofStatus.textContent='FINAL AUTHORITY SATISFIED';els.gateProofResult.textContent='COMMITTED';els.gateProofCode.textContent='DECISION → REPAIR → APPROVAL → PASS';els.gateProofCopy.textContent='The agent stayed inside the authorized decision space and committed only after explicit final approval.';return;}els.gateProofStatus.textContent='NOT REACHED';els.gateProofResult.textContent='WAITING';els.gateProofCode.textContent='FINAL_COMMIT_APPROVAL_REQUIRED';}
function makeReceiptId(){const seed=`${state.scenarioId}|${state.selectedPlanId}|${JSON.stringify(state.repairedPlan?.metrics)}|${state.toolCalls}|${state.humanDecisions}`;let h=2166136261;for(const ch of seed)h=Math.imul(h^ch.charCodeAt(0),16777619);return `VMC-${(h>>>0).toString(16).padStart(8,'0').toUpperCase()}`;}
function renderReceipt(){if(!state.committed){els.receiptEmpty.classList.remove('hidden');els.receipt.classList.add('hidden');return;}els.receiptEmpty.classList.add('hidden');els.receipt.classList.remove('hidden');els.receiptSummary.textContent=`${scenario().finalSummary(state.repairedPlan)} · decision + repair + final approval recorded`;els.metricOptions.textContent=String(scenario().candidates.length);els.metricDecisions.textContent=String(state.humanDecisions);els.metricRepairs.textContent=String(state.repairs);els.receiptId.textContent=state.receiptId;}
function lockGoalContract(){state.goalLocked=true;els.contractSeal.textContent=`Goal Contract locked · ${scenario().goal.seal}`;els.contractSeal.classList.add('locked');els.lockGoalBtn.disabled=true;addEvent('human',`Human locked ${scenario().label} Goal Contract`);return {ok:true,scenario:state.scenarioId,constraints:scenario().goal.constraints.map(c=>({...c}))};}
function requireGoal(){return state.goalLocked?null:{ok:false,error:'GOAL_CONTRACT_NOT_LOCKED',next:'Human must lock the Goal Contract first.'};}
function toolGetGoalContract(){countTool('get_goal_contract');const b=requireGoal();if(b)return b;return {ok:true,scenario:{id:scenario().id,label:scenario().label},goal:scenario().goal.title,constraints:scenario().goal.constraints.map(c=>({...c})),authority:'Agent may explore, plan, verify, and repair. Human judgment is required to expand authority and to commit irreversible actions.'};}
function toolDiscoverOptions(){countTool('discover_options');const b=requireGoal();if(b)return b;state.optionsDiscovered=true;renderOptions();addEvent('tool',`${scenario().label} option space discovered`);return {ok:true,scenario:state.scenarioId,options:scenario().options};}
function toolGeneratePlans(){countTool('generate_candidate_plans');if(!state.optionsDiscovered)return {ok:false,error:'OPTIONS_NOT_DISCOVERED'};state.compression=compressDecisionFrontier(scenario().candidates,scenario().goal.constraints);state.frontier=state.compression.frontier;state.plansGenerated=true;renderPlans();addEvent('tool',`${scenario().candidates.length} candidates compressed to ${state.frontier.length} human-relevant trade-offs`);return {ok:true,scenario:state.scenarioId,raw_plan_count:scenario().candidates.length,rejected_or_dominated:state.compression.rejected,frontier:state.frontier};}
function toolVerifyPlans(){countTool('verify_candidate_plans');if(!state.plansGenerated)return {ok:false,error:'PLANS_NOT_GENERATED'};state.plansVerified=true;const verified=state.frontier.map(p=>{const e=evaluatePlan(p,scenario().goal.constraints);return {plan_id:p.id,checks:e.checks,failed_constraints:e.failed.map(c=>c.id),full_pass:e.fullPass,tradeoff:p.tradeoff};});addEvent(state.compression.originalGoalFeasible?'pass':'fail',state.compression.originalGoalFeasible?'Original Goal Contract is feasible':'No zero-trade-off plan satisfies the original Goal Contract');return {ok:true,scenario:state.scenarioId,original_goal_feasible:state.compression.originalGoalFeasible,verified,decision_required:!state.compression.originalGoalFeasible};}
function toolRequestDecision(){countTool('request_human_decision');if(!state.plansVerified)return {ok:false,error:'PLANS_NOT_VERIFIED'};state.decisionRequested=true;renderDecisionPackage();addEvent('human',`Human Decision Package requested · ${state.frontier.length} compressed trade-offs`);return {ok:true,status:'AWAITING_HUMAN_TRADEOFF_DECISION',scenario:state.scenarioId,decisions:state.frontier.map(p=>({plan_id:p.id,tradeoff:p.tradeoff,summary:p.summary})),note:'This tool cannot authorize a trade-off. Human UI action is required.'};}
function humanAuthorizePlan(planId){const config=scenario().authorityByPlan[planId];if(!state.decisionRequested||!config)return false;state.decisionAuthorized=true;state.selectedPlanId=planId;state.authorityEnvelope=createAuthorityEnvelope(scenario().goal.constraints,config);state.humanDecisions++;els.decisionStatus.classList.add('authorized');els.decisionStatus.textContent=`AUTHORIZED · ${state.authorityEnvelope.label} · ${state.authorityEnvelope.rationale}`;els.decisionGrid.querySelectorAll('button').forEach(b=>b.disabled=true);addEvent('human',`Human authorized bounded trade-off · ${state.authorityEnvelope.label}`);continueAuthorizedPlan(planId);return true;}
async function continueAuthorizedPlan(planId){const s=scenario(),plan=s.candidates.find(p=>p.id===planId);setStage(4,'Decision recorded. AI executes inside the bounded authority envelope.',els.executionPanel);focusDemo(els.executionPanel);state.executionStarted=true;renderExecutionState('RUN',`Executing ${plan.label}`,plan.summary);repairStep('pass','Plan authorized',`${plan.composition.join(' + ')} · ${s.finalSummary(plan)}`);if(s.disruption?.appliesTo===planId){await sleep(900);injectDisruption();await sleep(800);await invokeTool('repair_plan');}else{state.repaired=true;state.repairedPlan=plan;repairStep('pass','No local repair required','The selected plan remains valid inside the authorized envelope.');}await sleep(700);await invokeTool('request_final_approval');demoRunning=false;}
function injectDisruption(){const d=scenario().disruption;if(!d||d.appliesTo!==state.selectedPlanId||state.disruptionInjected)return;state.disruptionInjected=true;renderExecutionState('!',d.title,d.copy);repairStep('fail','Execution disruption',d.event);addEvent('fail',d.event);}
function toolRepairPlan(){countTool('repair_plan');if(!state.decisionAuthorized)return {ok:false,error:'HUMAN_DECISION_REQUIRED'};if(!state.disruptionInjected)return {ok:true,repair_needed:false,plan:state.repairedPlan};const choice=chooseAuthorizedRepair(scenario().repairCandidates,state.authorityEnvelope);if(!choice.selected)return {ok:false,error:'REPAIR_OUTSIDE_AUTHORIZED_ENVELOPE',evaluated:choice.evaluated.map(x=>({plan_id:x.plan.id,failed:x.failed.map(c=>c.id)}))};state.repaired=true;state.repairs++;state.repairedPlan=choice.selected;renderExecutionState('PASS','Plan repaired inside authorized bounds',choice.selected.summary);repairStep('pass','Autonomous local repair',`${choice.selected.composition.join(' + ')} · ${scenario().finalSummary(choice.selected)}`);repairStep('pass','Authority check','Every repaired metric remains inside the human-approved envelope.');addEvent('pass','Plan repaired without expanding human authority');setStage(5,'Repair succeeded inside the authorized envelope. Final commitment is still human-controlled.',els.authorityPanel);return {ok:true,repaired:true,plan:choice.selected,authority_check:'PASS',human_reapproval_required_for_repair:false};}
function toolRequestFinalApproval(){countTool('request_final_approval');if(!state.repaired||!state.repairedPlan)return {ok:false,error:'PLAN_NOT_READY'};state.finalApprovalRequested=true;renderGate('blocked');els.finalApprovalBox.classList.remove('hidden');els.finalApprovalCopy.textContent=scenario().finalSummary(state.repairedPlan);addEvent('human','Final irreversible commitment requires explicit human approval');focusDemo(els.authorityPanel);return {ok:true,status:'AWAITING_FINAL_HUMAN_APPROVAL',scenario:state.scenarioId,plan:state.repairedPlan};}
function humanApproveFinal(){if(!state.finalApprovalRequested||!state.repaired)return false;state.finalApproved=true;state.humanDecisions++;els.finalApprovalBox.classList.add('hidden');addEvent('human','Human approved final irreversible commitment');return true;}
function toolCommitPlan(){countTool('commit_plan');if(!state.decisionAuthorized)return {ok:false,error:'HUMAN_TRADEOFF_DECISION_REQUIRED'};if(!state.repaired||!state.repairedPlan)return {ok:false,error:'PLAN_NOT_VERIFIED_READY'};if(!state.finalApproved){renderGate('blocked');addEvent('fail','Commit blocked · FINAL_COMMIT_APPROVAL_REQUIRED');return {ok:false,error:'FINAL_COMMIT_APPROVAL_REQUIRED',next:'Wait for explicit human final approval.'};}if(!authorityAllows(state.repairedPlan,state.authorityEnvelope))return {ok:false,error:'FINAL_PLAN_OUTSIDE_AUTHORIZED_ENVELOPE'};state.committed=true;state.receiptId=makeReceiptId();renderGate('committed');renderReceipt();addEvent('pass','Goal achieved · final plan committed inside human authority');setStage(7,'Mission complete. The receipt explains the goal, trade-off, repair, approvals, and final outcome.',els.evidencePanel);focusDemo(els.evidencePanel);return {ok:true,status:'GOAL_ACHIEVED',scenario:state.scenarioId,final_plan:state.repairedPlan,receipt_id:state.receiptId};}
function toolReceipt(){countTool('get_evidence_receipt');return {ok:true,scenario:{id:scenario().id,label:scenario().label},goal_status:state.committed?'PASS':'IN_PROGRESS',original_goal:{title:scenario().goal.title,constraints:scenario().goal.constraints},plan_compression:state.compression?{raw:scenario().candidates.length,rejected_or_dominated:state.compression.rejected,human_relevant:state.frontier.length}:null,human_tradeoff_decision:state.authorityEnvelope?{id:state.authorityEnvelope.id,label:state.authorityEnvelope.label,rationale:state.authorityEnvelope.rationale}:null,execution_disruption:state.disruptionInjected?scenario().disruption.event:null,autonomous_repair:state.repairedPlan,final_human_approval:state.finalApproved,human_decisions:state.humanDecisions,receipt_id:state.receiptId,recent_events:state.events.slice(0,10)};}
const emptySchema={type:'object',properties:{},additionalProperties:false};
const toolDefinitions=[
{name:'get_goal_contract',title:'Read Goal Contract',description:'Read the active scenario, locked human goal, hard constraints, and authority model.',inputSchema:emptySchema,annotations:{readOnlyHint:true},execute:toolGetGoalContract},
{name:'discover_options',title:'Discover Options',description:'Discover the option space and the constraints exposed by the active domain scenario.',inputSchema:emptySchema,annotations:{readOnlyHint:false},execute:toolDiscoverOptions},
{name:'generate_candidate_plans',title:'Generate Candidate Plans',description:'Evaluate candidate plans and compress them into the non-dominated human decision frontier.',inputSchema:emptySchema,annotations:{readOnlyHint:false},execute:toolGeneratePlans},
{name:'verify_candidate_plans',title:'Verify Candidate Plans',description:'Verify candidate plans against the immutable Goal Contract and identify required trade-offs.',inputSchema:emptySchema,annotations:{readOnlyHint:false},execute:toolVerifyPlans},
{name:'request_human_decision',title:'Request Human Trade-off Decision',description:'Present only the meaningful trade-offs. This tool cannot expand authority itself.',inputSchema:emptySchema,annotations:{readOnlyHint:false},execute:toolRequestDecision},
{name:'repair_plan',title:'Repair Authorized Plan',description:'Select an authorized repair candidate without expanding the human-approved decision envelope.',inputSchema:emptySchema,annotations:{readOnlyHint:false},execute:toolRepairPlan},
{name:'request_final_approval',title:'Request Final Approval',description:'Stop at the irreversible action boundary and request explicit human approval.',inputSchema:emptySchema,annotations:{readOnlyHint:false},execute:toolRequestFinalApproval},
{name:'commit_plan',title:'Commit Final Plan',description:'Commit only after verification, bounded authority checks, and explicit final human approval.',inputSchema:emptySchema,annotations:{readOnlyHint:false},execute:toolCommitPlan},
{name:'get_evidence_receipt',title:'Get Decision Provenance Receipt',description:'Read the goal, compression, human authority, repair lineage, final approval, and verified outcome.',inputSchema:emptySchema,annotations:{readOnlyHint:true},execute:toolReceipt}
];
function renderToolChips(){els.toolChips.innerHTML=toolDefinitions.map(t=>`<span class="tool-chip">${t.name}()</span>`).join('');}
async function registerWebMCPTools(){const mc=document.modelContext;if(!mc?.registerTool){nativeExecutionReady=false;els.webmcpStatus.innerHTML='<span class="dot"></span>WebMCP preview mode';els.nativeExecutionMode.textContent='PREVIEW FALLBACK · native API unavailable';return false;}try{for(const t of toolDefinitions)await mc.registerTool(t);const registered=await mc.getTools();nativeModelContext=mc;nativeToolsByName=Object.fromEntries(registered.filter(t=>toolDefinitions.some(d=>d.name===t.name)).map(t=>[t.name,t]));nativeExecutionReady=toolDefinitions.every(t=>nativeToolsByName[t.name]);els.webmcpStatus.classList.add('ready');els.webmcpStatus.innerHTML=`<span class="dot"></span>${toolDefinitions.length} WebMCP tools live`;els.nativeExecutionMode.textContent=nativeExecutionReady?'LIVE · document.modelContext.executeTool()':'REGISTERED · execution lookup incomplete';addEvent('pass',`${toolDefinitions.length} native WebMCP tools registered`);return nativeExecutionReady;}catch(e){console.error(e);nativeExecutionReady=false;els.webmcpStatus.innerHTML='<span class="dot"></span>WebMCP registration error';els.nativeExecutionMode.textContent='REGISTRATION ERROR';return false;}}
function resetMission(){state=freshState();demoRunning=false;els.lockGoalBtn.disabled=false;els.contractSeal.textContent='Contract unlocked';els.contractSeal.classList.remove('locked');els.marketEmpty.classList.remove('hidden');els.supplierList.innerHTML='';els.rawPlanCount.textContent='0';els.rejectedPlanCount.textContent='0';els.decisionPlanCount.textContent='0';els.planGrid.innerHTML='';els.decisionGrid.innerHTML='';els.decisionStatus.classList.remove('authorized');els.decisionStatus.textContent='No human trade-off decision recorded.';renderExecutionState('WAIT','Waiting for an authorized plan','Execution starts only after the human decision package is resolved.');els.repairFlow.innerHTML='';renderGate('waiting');els.finalApprovalBox.classList.add('hidden');els.receipt.classList.add('hidden');els.receiptEmpty.classList.remove('hidden');renderTimeline();stageIds.forEach(id=>els[id].classList.remove('active','complete'));els.demoNarration.textContent='Ready — press Run the decision demo';els.runDemoBtn.disabled=false;els.runDemoBtn.textContent='Run the decision demo';resetNativeTrace();renderScenarioShell();}
function selectScenario(id){if(!scenarios[id]||demoRunning)return false;currentScenarioId=id;resetMission();addEvent('human',`Scenario selected · ${scenario().label}`);return true;}
async function runDecisionDemo(){if(demoRunning)return;resetMission();if(registrationPromise)await registrationPromise;demoRunning=true;els.runDemoBtn.disabled=true;els.runDemoBtn.textContent=nativeExecutionReady?'Native WebMCP running...':'Preview demo running...';setStage(0,'Human defines the outcome and authority boundary.',els.contractPanel);focusDemo(els.contractPanel);lockGoalContract();await sleep(500);await invokeTool('get_goal_contract');setStage(1,'AI explores the active domain option space.',els.marketPanel);focusDemo(els.marketPanel);await sleep(500);await invokeTool('discover_options');await sleep(850);setStage(2,'The generic engine evaluates candidates and compresses them into human-relevant trade-offs.');focusDemo(els.planSection);await invokeTool('generate_candidate_plans');await sleep(650);await invokeTool('verify_candidate_plans');await sleep(850);setStage(3,'No zero-trade-off answer exists. Human judgment is required only for the compressed frontier.');focusDemo(els.decisionSection);await invokeTool('request_human_decision');els.runDemoBtn.textContent='Waiting for human trade-off';demoRunning=false;}
els.lockGoalBtn.addEventListener('click',()=>{if(!state.goalLocked)lockGoalContract()});
els.runDemoBtn.addEventListener('click',runDecisionDemo);
els.resetBtn.addEventListener('click',resetMission);
els.scenarioSwitcher.querySelectorAll('[data-scenario]').forEach(b=>b.addEventListener('click',()=>selectScenario(b.dataset.scenario)));
els.finalApproveBtn.addEventListener('click',async()=>{if(!humanApproveFinal())return;setStage(6,'Final human approval recorded. The same native commit tool may now complete.',els.authorityPanel);await sleep(500);const r=await invokeTool('commit_plan');if(r.ok){await invokeTool('get_evidence_receipt');els.runDemoBtn.disabled=false;els.runDemoBtn.textContent='Replay decision demo';}});
window.verifiedMissionControl={get state(){return state},get nativeExecutionReady(){return nativeExecutionReady},get scenarioId(){return currentScenarioId},selectScenario,resetMission,lockGoalContract,humanAuthorizePlan,humanApproveFinal,runDecisionDemo,invokeTool,tools:Object.fromEntries(toolDefinitions.map(t=>[t.name,t.execute]))};
renderToolChips();resetMission();registrationPromise=registerWebMCPTools();
